# Generated by Django 6.0.6 on 2026-06-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('universidad', 'Universidad'), ('entretenimiento', 'Entretenimiento'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=50)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'categoria', 'mes', 'anio')},
            },
        ),
    ]
